[package]
name = "Day1"
version = "0.1.0"
authors = ["Pedro Rodrigues <csixteen@proton.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-core = { version = "0.1.0", path = "../../../lib/Rust/aoc" }
